### ISSUE TITLE
Develop Khmer unicode NiDA for ubuntu 

### ISSUE THREAD

**Issue by samreachyan** [socheatsok78/khmer-unicode-keyboard-for-macos#2]
បង តើបងអាចអភិវឌ្ឍន៍ Khmer unicode NiDA layout នៅលើ ubuntu បានទេ? ព្រោះខ្ញុំប្រើវា នៅមានបញ្ហា ស្រៈមួយចំនួនដូចជាពាក្យ ឈ្មោះ = ឈ + ្ +​ ម +​ ោ + ះ​ យើងមិនអាចសរសេរ ឈ +្​+ម+ោះ តែម្តងបានទៅ(៉វាមិនមានស្រៈមកស្រាប់ទេ ដូចជា​ ាំ ោះ េះ )។ វានៅមានស្រៈមួយចំនួនផ្សេងទៀតត្រូវប្រើ key ផ្សេងដើម្បីបំពេញអក្សរ។ និយាយរួមគឺចំនាយពេលវាយ ជាងការប្រើ NiDA keyboard លើ windows ដែលមានស្រៈទាំងនោះស្រាប់តែម្តង. មួយទៀត ខ្ញុំបានរកមើល unicode character table ឃើញថា អក្សរខ្មែរយើងអត់មាន ស្រៈ ាំ ុះ​ េះ ោះ នៅលើ unicode ស្រាប់ទេ​ តើបងធ្វើដូចម្តេចដើម្បីភ្ជាប់អក្សរ ពេលយើងចុចតែមួយ key (នៅលើ key map "a" <AC01> < ា,  ,​ ,​ , ​> អត់មានស្រៈ ាំ ទេនៅលើ​unicode key) តើបងមានវិធីសាស្រ្តដោះស្រាយដូចម្តេច (នៅលើ ubuntu shift+a = nothing happen, នៅលើ​ window shift + a = ាំ )?

**Comment by socheatsok78** [comment]
Hello @samreachyan , Khmer Unicode on Ubuntu is fully support NiDA layout. Your system might be using `ibus` input method. Please change it to `xim` in you `System Settings -> Language Support -> Keyboard input method system`, change it from `ibus` to `xim` then reboot your system.

**Comment by samreachyan** [comment]
Thanks you brother!!!

**Comment by cmengkorng** [comment]
i still face this issue after i changed it. what should i do ?

**Comment by khosokha** [comment]
it still faces this issue on Ubuntu 22.04LTS

**Comment by samreachyan** [comment]
> it still faces this issue on Ubuntu 22.04LTS

Keep in mind that, ubuntu support with Khmer keyboard a little bit difference from window. Just use the default Khmer keyboard layout on it.  ាំ = ា +  ំ, and another vowel also.
